// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHSQKfs4LHTds9ZIph8OhQAUYX5VJIu4g',
    appId: '1:988167390491:web:3413a066601c84dacfbfbe',
    messagingSenderId: '988167390491',
    projectId: 'schoolappio-42608',
    authDomain: 'schoolappio-42608.firebaseapp.com',
    storageBucket: 'schoolappio-42608.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpbqHoPez7ME9VPRHkNPj3Y2GFI-z-N_s',
    appId: '1:988167390491:android:47f91976249f661bcfbfbe',
    messagingSenderId: '988167390491',
    projectId: 'schoolappio-42608',
    storageBucket: 'schoolappio-42608.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiZTvLoX9XyZlSnjYhGx51ZXEovzuBswY',
    appId: '1:988167390491:ios:5e6f7cdee962bcc4cfbfbe',
    messagingSenderId: '988167390491',
    projectId: 'schoolappio-42608',
    storageBucket: 'schoolappio-42608.appspot.com',
    iosBundleId: 'com.example.schoolappio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiZTvLoX9XyZlSnjYhGx51ZXEovzuBswY',
    appId: '1:988167390491:ios:5e6f7cdee962bcc4cfbfbe',
    messagingSenderId: '988167390491',
    projectId: 'schoolappio-42608',
    storageBucket: 'schoolappio-42608.appspot.com',
    iosBundleId: 'com.example.schoolappio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHSQKfs4LHTds9ZIph8OhQAUYX5VJIu4g',
    appId: '1:988167390491:web:b5cb023f98fd53d9cfbfbe',
    messagingSenderId: '988167390491',
    projectId: 'schoolappio-42608',
    authDomain: 'schoolappio-42608.firebaseapp.com',
    storageBucket: 'schoolappio-42608.appspot.com',
  );
}
